version: 2

sources:
    - name: staging
      database: mystical-nimbus-338219
      schema: trips_data_all

      tables:
      - name: green_tripdata_external_table
      - name: fhv_tripdata_external_table
      - name: yellow_tripdata_external_table